apiVersion: v1
kind: Service
metadata:
  name: helm-prometheus-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helm-prometheus-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
