apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-prometheus-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tailszhang0/helm-prometheus-demo.git
    targetRevision: HEAD
    path: charts/helm-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-prometheus
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
