namespace: helm-prometheus
app:
  image: tails1982/helm-prometheus-app
  tag: "4"
  port: 5000
  replicas: 1
prometheus:
  image: prom/prometheus
  port: 9090
grafana:
  image: grafana/grafana
  port: 3000
